### ISSUE TITLE
Add threads for SQS redoer producer

### ISSUE THREAD

**Issue by roncewind** [Senzing/redoer#107]
- check SQS queue, if it has 100 or 1000 records, wait 0.1s
- use 4 threads to read SYS_EVAL_QUEUE(?) and push to SQS input queue
-

**Comment by roncewind** [comment]
possibly remove `DelaySeconds=10,`  from `self.sqs.send_message`. Such a parameter exists on the queue, maybe set it there instead of per message.

**Comment by roncewind** [comment]
increase the internal queue size from 10 to 100 or 200

**Comment by docktermj** [comment]
Pull Requests:

- https://github.com/Senzing/redoer/pull/111
