### ISSUE TITLE
Documentation missing for subcommand modes

### ISSUE THREAD

**Issue by brianmacy** [Senzing/redoer#53]
**Describe the bug**
None of the withinfo or processing queue modes are documented or mentioned.

**To Reproduce**
Look for kafka, rabbit, sqs, etc

**Additional context**
I noticed tempalte-python.py is still referenced in the usage so I just think the docs were never completed for this task.

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/redoer/pull/54

**Comment by docktermj** [comment]
@brianmacy If the new documentation satisfies your concerns, please close this issue.

**Comment by docktermj** [comment]
@brianmacy What you may be looking for is one redoer writing to a queue and one or more redoers reading from the queue.

An example of this is seen in a docker-compose.yaml file:
https://github.com/Senzing/docker-compose-demo/blob/1840cf68afdb6ac38b398f7b0b36b7145d6fe53c/resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-rabbitmq-withinfo.yaml#L173-L223
